import { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import Sidebar from '../components/Sidebar';
import { getCampaigns, createCampaign, toggleCampaign } from '../services/api';

const PromotionsPage = () => {
  const { shopId } = useParams();
  const [campaigns, setCampaigns] = useState([]);
  const [loading, setLoading] = useState(true);
  const [newCode, setNewCode] = useState('');
  const [newDiscount, setNewDiscount] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [errorDesc, setErrorDesc] = useState('');

  useEffect(() => {
    fetchCampaigns();
  }, [shopId]);

  const fetchCampaigns = async () => {
    try {
      setLoading(true);
      const res = await getCampaigns(shopId);
      setCampaigns(res.data.data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handeCreate = async (e) => {
    e.preventDefault();
    setSubmitting(true);
    setErrorDesc('');
    try {
      await createCampaign(shopId, { code: newCode, discountPercentage: newDiscount });
      setNewCode('');
      setNewDiscount('');
      fetchCampaigns();
    } catch (err) {
      setErrorDesc(err.response?.data?.message || 'Failed to create campaign');
    } finally {
      setSubmitting(false);
    }
  };

  const handleToggle = async (campaignId) => {
    try {
      await toggleCampaign(shopId, campaignId);
      fetchCampaigns();
    } catch (err) {
      console.error(err);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 flex">
      <Sidebar />
      <main className="flex-1 ml-56 p-8">
        <header className="mb-8">
          <h1 className="text-2xl font-bold text-gray-900">Promotions & Campaigns</h1>
          <p className="text-gray-500">Track usage and revenue generated by specific promotional coupons.</p>
        </header>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="lg:col-span-1">
            <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100">
              <h2 className="text-lg font-bold text-gray-900 mb-4">Create Promo Code</h2>
              <form onSubmit={handeCreate} className="space-y-4">
                <div>
                  <label className="block text-xs font-bold text-gray-400 uppercase mb-2">Code</label>
                  <input
                    type="text"
                    required
                    placeholder="e.g. SUMMER20"
                    value={newCode}
                    onChange={(e) => setNewCode(e.target.value.toUpperCase())}
                    className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl focus:outline-none focus:border-primary-500 focus:bg-white text-sm font-bold tracking-widest text-gray-800"
                  />
                </div>
                <div>
                  <label className="block text-xs font-bold text-gray-400 uppercase mb-2">Discount %</label>
                  <input
                    type="number"
                    required
                    min="1"
                    max="100"
                    placeholder="e.g. 15"
                    value={newDiscount}
                    onChange={(e) => setNewDiscount(e.target.value)}
                    className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl focus:outline-none focus:border-primary-500 focus:bg-white text-sm"
                  />
                </div>
                {errorDesc && <p className="text-xs text-red-500">{errorDesc}</p>}
                <button
                  type="submit"
                  disabled={submitting}
                  className="w-full py-3 bg-primary-600 text-white font-bold rounded-xl shadow-md hover:bg-primary-700 transition-colors disabled:opacity-50"
                >
                  {submitting ? 'Creating...' : 'Launch Campaign'}
                </button>
              </form>
            </div>
          </div>

          <div className="lg:col-span-2">
            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
              <div className="p-6 border-b border-gray-100 flex justify-between items-center">
                <h2 className="text-lg font-bold text-gray-900">Active & Past Campaigns</h2>
              </div>

              {loading ? (
                <div className="p-6 text-gray-500 text-sm">Loading campaigns...</div>
              ) : campaigns.length === 0 ? (
                <div className="p-10 text-center flex flex-col items-center">
                  <div className="w-16 h-16 bg-gray-50 rounded-full flex justify-center items-center mb-4">
                    <svg className="w-8 h-8 text-gray-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v13m0-13V6a2 2 0 112 2h-2zm0 0V5.5A2.5 2.5 0 109.5 8H12zm-7 4h14M5 12a2 2 0 110-4h14a2 2 0 110 4M5 12v7a2 2 0 002 2h10a2 2 0 002-2v-7" />
                    </svg>
                  </div>
                  <h3 className="text-gray-900 font-bold mb-1">No campaigns active</h3>
                  <p className="text-sm text-gray-500">Create a promotional code to trace POS marketing usage.</p>
                </div>
              ) : (
                <div className="overflow-x-auto">
                  <table className="w-full text-left border-collapse">
                    <thead>
                      <tr className="bg-gray-50/50">
                        <th className="px-6 py-4 pb-2 border-b border-gray-100 text-xs font-bold text-gray-400 uppercase tracking-wider">Promo Code</th>
                        <th className="px-6 py-4 pb-2 border-b border-gray-100 text-xs font-bold text-gray-400 uppercase tracking-wider">Discount</th>
                        <th className="px-6 py-4 pb-2 border-b border-gray-100 text-xs font-bold text-gray-400 uppercase tracking-wider text-center">Uses</th>
                        <th className="px-6 py-4 pb-2 border-b border-gray-100 text-xs font-bold text-gray-400 uppercase tracking-wider text-right">Revenue Generated</th>
                        <th className="px-6 py-4 pb-2 border-b border-gray-100 text-xs font-bold text-gray-400 uppercase tracking-wider text-right">Status</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-50">
                      {campaigns.map((c) => (
                        <tr key={c._id} className="hover:bg-gray-50/50 transition-colors">
                          <td className="px-6 py-4 font-bold text-gray-900 tracking-wider text-sm">
                            {c.code}
                          </td>
                          <td className="px-6 py-4 flex items-center gap-2">
                            <span className="bg-emerald-100 text-emerald-700 text-xs font-bold px-2 py-1 rounded-md">-{c.discountPercentage}%</span>
                          </td>
                          <td className="px-6 py-4 text-center font-semibold text-gray-700 text-sm">
                            {c.usageCount}
                          </td>
                          <td className="px-6 py-4 text-right font-bold text-primary-600 text-sm">
                            ${c.revenueGenerated.toFixed(2)}
                          </td>
                          <td className="px-6 py-4 text-right">
                            <button
                              onClick={() => handleToggle(c._id)}
                              className={`text-xs font-bold px-3 py-1.5 rounded-lg border ${c.isActive ? 'border-red-200 text-red-600 hover:bg-red-50' : 'border-emerald-200 text-emerald-600 hover:bg-emerald-50'}`}
                            >
                              {c.isActive ? 'Disable' : 'Enable'}
                            </button>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default PromotionsPage;
